### PR TITLE
Tweak README example to be clearer

### PR DESCRIPTION
**Pull request by Arnavion**
Both the crate and the macro in the original text were named "my_macro",
so it was not obvious which one corresponded to what. This commit names them
"foo-macros" and "bar".

Also, the original text talked about the "my_macros" crate and the shim crate,
but the shim crate deserves to have the name the user gave to the original
pre-watt crate, since that is what gets published to crates.io.
The text now walks the user through renaming "foo-macros" to "foo-macros-impl"
and naming the shim crate "foo-macros".

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
Thanks!

I had a few too many PRs stack up in the last week but I'll review this as soon as I can.

**Review by dtolnay — COMMENTED** [review]
Thanks for the PR, I agree that the original writing wasn't clear. I pushed https://github.com/dtolnay/watt/compare/cc6a8bad8207a17206660e03bd3ccfbe0a2e4f6a...b79042e8ef7269398fc078ec07c99de4664578d6 to address this.

**Comment by Arnavion** [comment]
I would've liked the part about renaming the original crate to -impl to be left in.

**Comment by dtolnay** [comment]
It's not a necessary step. I would tend to give the shim the same name as suggested in the update. There shouldn't be steps in the readme that aren't needed.

**Comment by Arnavion** [comment]
>It's fine to give this the same crate name as the
>previous crate, since the other one won't be getting published to crates.io. In
>a new Cargo.toml, put:

And where does the reader put this new "Cargo.toml" which is supposed to be for a crate with the same name "my_macros", when the directory for `my_macros` already has the original crate?

There are two parts to renaming. The directory and the crate name. It's fine if you don't want to rename the crate, but I would've liked to keep the part that mentions renaming the directory.

See for example the demo in this very repo: https://github.com/dtolnay/watt/tree/master/demo/impl

**Pull request closed without merging**
